<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/08/04 14:25:20

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => '123456',
  'name' => 'doctrine',
)),);
